function getStateCity (){

    return {
        'Kedah' : [
            'alor setar',
            'jitra',
            'sungai petani',
            'Gurun',
            'Kuala Kedah',
            'Langkawi',
        ],
        'Pulau Pinang' : [
            'Balik Pulau',
            'Batu Ferringhi',
            'Butterworth',
            'Kepala Batas',
            'Bayan Lepas',
        ],
        'Perak' : [
            'Ipoh',
            'Taiping',
            'Lumut',
            'Teluk Intan',
            'Tapah',
            'Gopeng',
            'Kuala Kangsar',
        ],
        'Selangor' : [
            'Shah Alam',
            'Klang',
            'Cyberjaya',
            'Puchong',
            'Dengkil',
            'Cheras',
            'Bangi',
            'Kajang ',   
        ],
        'Kuala Lumpur' : [
            'Ampang',
            'Cheras',
            'Sentul',
        ],
        'Johor' : [
            'Johor Bharu',
            'Kluang',
            'Muar',
            'Mersing',
            'Batu Pahat',
            'Segamat',
            'Kota Tinggi',
        ],
        'Negeri Sembilan' : [
            'Seremban',
            'Nilai',
            'Rembau',
            'Port Dickson',
            'Tampin',
            'Kuala Pilah',
        ],
        'Pahang' : [
            'Kuantan',
            'Temerloh',
            'Brinchang',
            'Maran',
            'Mentakab',
            'Jerantut',
        ],
        'Sabah' : [
            'Kota Kinabalu',
            'Sandakan',
            'Tawau',
            'Semporna',
            'Kinabatangan',
            'Kundasang',
        ],
        'Sarawak' :[
            'Kuching',
            'Miri',
            'Bintulu',
            'Betong',
            'Sibu',
        ],
        'Kelantan' : [
            'Kota Bharu',
            'Gua Musang',
            'Pasir Mas',
            'Jeli',
            'Tumpat',
            'Tanah Merah',
        ],
        'Melaka' : [
            'Alor Gajah',
            'Jasin',
            'Klebang Besar',
            'Ayer Keroh',
            'Bukit Rambai',
        ],
        'Terengganu':[
            'Kuala Terengganu',
            'Kuala Besut',
            'Kemaman',
            'Marang',
            'Kuala Dungun',
        ],
        'Perlis' : [
            'Kuala Perlis',
            'Kangar',
            'Arau',
            'Padang Besar',
            'Wang Kelian',
        ]

    }
 
};